[[main]]
    name = "About"
    pageRef = "about"
    weight = 10

[[main]]
    name = "Posts"
    pageRef = "posts"
    weight = 20

[[main]]
    name = "Projects"
    pageRef = "Projects"
    weight = 30

[[main]]
    name = "Resume"
    pageRef = "Resume"
    weight = 40

[[footer]]
    name = "Tags"
    pageRef = "tags"
    weight = 10

[[footer]]
    name = "Categories"
    pageRef = "categories"
    weight = 20

[[footer]]
    name = "Authors"
    pageRef = "authors"
    weight = 30
