version: '3.8'

services:
  hugo-nginx:
    image: "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: hugo_nginx_site
